### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by CyberRubyFox** [theriou/Satchel-Scanner#2]
Another user had Satchel Scanner enabled but not running. When checking memory usage he noted this was at 1.5gb (1,514.13 mb) of memory used. At the same time, mine was setup the same and using under 200 kb of memory. 

Let me know what info is needed to isolate.

**Comment by theriou** [comment]
For SatchelScanner specifically (the current version)?

Would probably need something like Settings used in it to try to replicate.

Like your figure, I've personally not seen anything crazy about its usage myself, and addons generally I think have garbage collection too to keep it from getting too crazy.

Otherwise only thing can think of is possibly addons interfering with each other.
